### ISSUE TITLE
Use of decapoda-research/llama-7b-hf checkpoint for the LLaMa-7B

### ISSUE THREAD

**Issue by twidddj** [tatsu-lab/alpaca_farm#41]
In my test, when [decapoda-research/llama-7b-hf](https://huggingface.co/decapoda-research/llama-7b-hf) checkpoint model used for the LLaMa-7B, the released model seems not work. 

```
model_name_or_path = 'tatsu-lab/alpaca-farm-sft10k-wdiff'
model = model_cls.from_pretrained(model_name_or_path, **model_kwargs).eval()
tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, **tokenizer_kwargs)
model_raw = load_raw_model('decapoda-research/llama-7b-hf', device)
reconstruct_tuned_model(model, model_raw)

source = tokenizer('What is the meaning of life?', return_tensors="pt", add_special_tokens=False)
inputs = source.input_ids
input_size = len(inputs[0])
output = model.generate(inputs=inputs.cuda(), temperature=0.7, do_sample=True, num_beams=1, max_new_tokens=100)

tokenizer.decode(output[0][input_size:], skip_special_tokens=True)
> 'mere latter whilst tout distinction namely coinc nam chang programme bef latter canon proph oracle tout nem sull ze nast mant appar bes appar fick moth rif oracle sup splendid mant bew splendid inse splend nem latter newer nun fick revel vor critics trou grud critics nam bes dar ze stup splend brig oracle stup splendid nun rapp grud trou nun nun nam litt parish parish nem divor mant revel devil splendid nem dal lud jan stan baz newer splendid rapp stan ruby rapp appar revel appar parish latter mighty ze litt bir mighty brig brig splend ga bew mighty'
```

**Comment by lxuechen** [comment]
Thanks for opening this issue! 

The released checkpoints are weight diffs between our models and **the Hugging Face checkpoint converted from Meta's released checkpoints based on newer versions of the transformers library (4.29.2)**. 

The `decapoda-research/llama-7b-hf` checkpoint is converted with transformers version 4.27.0.dev0, so there could be a mismatch in the layout of the weights. Note the code for the llama model in the transformers library has undergone substantial changes since March. 

We recommend converting Meta's released weights with the latest transformers library. I will improve the documentation on this. Closing this issue for now, but feel free to reopen if it still doesn't work after re-conversion.

**Comment by Yuhuajoe** [comment]
Hi, i have a similar questions , when i recover alpaca-farm-ppo-sim model, i got a different model_sum number(50837.671875), which should be equal to 50835.43359375 as expected. 
I  converted llama-7b-hf model from Meta's released checkpoints based on transformers==4.29.2 and i got correct result for sft-10k model after recovering model weights.
I'm wondering which reasons may cause this problem?

**Comment by lxuechen** [comment]
> Hi, i have a similar questions , when i recover alpaca-farm-ppo-sim model, i got a different model_sum number(50837.671875), which should be equal to 50835.43359375 as expected. I converted llama-7b-hf model from Meta's released checkpoints based on transformers==4.29.2 and i got correct result for sft-10k model after recovering model weights. I'm wondering which reasons may cause this problem?

Since the difference here is very small, one likely reason could be the data format. E.g., computing the diff in bfloat16 will result in different weight values than computing in float32.

**Comment by Yuhuajoe** [comment]
does that mean small difference is reasonable and i can trust the performance with recovered model?

**Comment by Yuhuajoe** [comment]
The base model i used was converted from Meta's released checkpoints via transformers==4.29.2.

**Comment by lxuechen** [comment]
> The base model i used was converted from Meta's released checkpoints via transformers==4.29.2.

Thanks for following up. Just to confirm, did you run our recovery script as it is (w/o modifications)?

**Comment by rtaori** [comment]
I see, very interesting. I will take a closer look at this next week to figure out what's going on. Our cluster is down for maintenance this week, apologize for the delay here, so I'll come back with an update next week once I can access the model checkpoints again.

**Comment by rtaori** [comment]
Hi @Yuhuajoe,
I am following up on this. I ran the following command
```
python -m pretrained_models.recover_model_weights \
  --llama-7b-hf-dir /juice5/scr5/nlp/llama_model/llama_hf_latest/llama-7b \
  --alpaca-farm-model-name ppo-sim \
  --models-save-dir /juice5/scr5/rtaori/tmp_alpaca_farm/
  ```
And I was able to reconstruct the `ppo-sim` weights with a matching `model_sum.txt` (no error in the script).


Can I suggest that you do the following again:
1. Re-convert the llama checkpoint with `transformers==4.29.2`,
2. Run the above command to auto-reconstruct the model weights.

The bug you're seeing could be either due to incorrect conversion or some issue in the wdiff pre-download you mentioned.

If you're still seeing an issue after this, please feel free to re-open this issue or create another issue post with the relevant details

**Comment by bpucla** [comment]
I also get the `integrity_check` error with `sft10k`.
The base ckpt was a raw Meta ckpt converted with `transformer=4.34.0`
Any insights would be appreciated!

The command is 
```
  python -m pretrained_models.recover_model_weights \
  --llama-7b-hf-dir <path1> \
  --alpaca-farm-model-name sft10k \
  --models-save-dir <path2>
```
